# tensorFlow basic syntax

In [1]:
import tensorflow as tf

/home/thesohankathait/anaconda3/envs/latest/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
print(tf.__version__)

1.9.0


In [3]:
# tensor = n dimensioanl array

In [4]:
hell = tf.constant("hello")

In [5]:
world = tf.constant("world")

In [6]:
type(hell)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hell)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
# to create tensreorFlow session

In [10]:
with tf.Session() as sess:
    result = sess.run(hell+world)

In [11]:
result

b'helloworld'

In [12]:
# b represent in above line as byte literal

In [13]:
a = tf.constant(10)

In [14]:
b = tf.constant(20)

In [15]:
type(a)

tensorflow.python.framework.ops.Tensor

In [16]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [17]:
a+b


<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [18]:
a+b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [20]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [21]:
result

30

In [24]:
const = tf.constant(10)


In [28]:
fill_mat = tf.fill((4,4),10)
fill_mat

<tf.Tensor 'Fill_1:0' shape=(4, 4) dtype=int32>

In [26]:
myzeros = tf.zeros((4,4))

In [27]:
myrandn = tf.random_normal((4,4),mean = 0, stddev = 1.0)

In [29]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [30]:
myrandu

<tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>

In [31]:
my_ops = [const,fill_mat,myzeros,myrandn,myrandu]

In [32]:
# for interactive session

In [33]:
sess = tf.InteractiveSession()

In [37]:
for op in my_ops:
    print(sess.run(op),sep="\n")
    print("\n\n")

10



[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



[[-0.6400417  -0.7950016  -0.5732528  -2.2890692 ]
 [ 2.800216    0.7544324   1.4377321  -0.69990957]
 [-0.4337343   0.80871254 -2.1651263  -0.5501979 ]
 [ 0.17814213  0.49222696 -0.51657516 -1.1870193 ]]



[[0.15345871 0.30927312 0.10485435 0.9845543 ]
 [0.8917999  0.8242947  0.6056341  0.288983  ]
 [0.78978693 0.60661256 0.9393344  0.5377196 ]
 [0.8944458  0.22451043 0.6143544  0.57158756]]





In [38]:
#or you can use like thiks

for op in my_ops:
    print(op.eval())
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-0.5610166  -0.7468221  -1.3529987  -0.87110615]
 [-0.6258865  -1.2053603  -2.0664115   1.2614007 ]
 [ 0.37125155 -0.16560829  1.4388118   0.7136998 ]
 [-0.06504829  0.28914434 -2.0400374  -1.6797186 ]]


[[0.03303063 0.92242694 0.10875285 0.01800835]
 [0.9832808  0.68743944 0.9395213  0.12093163]
 [0.47113693 0.7575426  0.0761261  0.2509396 ]
 [0.18947923 0.3951273  0.65117407 0.22671318]]




In [39]:
a = tf.constant([[1,2],
                [3,4]])

In [41]:
a.gbet_shape()

TensorShape([Dimension(2), Dimension(2)])

In [42]:
b=tf.constant([[10],[100]])

In [43]:
b

<tf.Tensor 'Const_7:0' shape=(2, 1) dtype=int32>

In [44]:
result = tf.matmul(a,b)

In [45]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [46]:
 result.eval()

array([[210],
       [430]], dtype=int32)

# TF Graphs


In [47]:
import tenssorflow as tf

In [48]:
n1 = tf.constant(1)

In [49]:
n2 = tf.constant(2)

In [50]:
n3 = n1+n2

In [51]:
with tf.Session() as sess:
    result  = sess.run(n3)

In [52]:
result

3

In [53]:
n3

<tf.Tensor 'add_6:0' shape=() dtype=int32>

In [54]:
print(tf.get_default_graph())

In [55]:
g = tf.Graph()

In [56]:
print(g)

In [57]:
graph_one = tf.get_default_graph()

In [58]:
print(graph_one)

In [59]:
graph_two = tf.Graph()

In [60]:
print(graph_two)

In [62]:
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

True


In [63]:
print(graph_two is tf.get_default_graph())

False


# TF Graphs

In [65]:
import tensorflow as tf

In [66]:
sess = tf.InteractiveSession()

/home/thesohankathait/anaconda3/envs/latest/lib/python3.6/site-packages/tensorflow/python/client/session.py:1714: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [67]:
my_tensor = tf.random_uniform((4,4),0,1)

In [68]:
my_tensor


<tf.Tensor 'random_uniform_1:0' shape=(4, 4) dtype=float32>

In [70]:
my_var = tf.Variable(initial_value=my_tensor)

In [71]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [73]:
# sess.run(my_var)

In [74]:
init = tf.global_variables_initializer()

In [75]:
sess.run(init)

In [76]:
sess.run(my_var)

array([[0.20118189, 0.09015906, 0.5092962 , 0.24797475],
       [0.3905313 , 0.8399565 , 0.9881325 , 0.7471541 ],
       [0.4745102 , 0.30901945, 0.15800536, 0.5003327 ],
       [0.25753677, 0.9957731 , 0.13754153, 0.682312  ]], dtype=float32)

In [77]:
# once you create
ph = tf.placeholder(dtype=tf.float32,shape=(None,5))